# Generated by Django 5.2.8 on 2025-12-08 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL-friendly identifier, e.g. 'ebooks', 'mock-tests'", max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('earn', 'Earn'), ('spend', 'Spend'), ('adjust', 'Adjust')], max_length=10)),
                ('source', models.CharField(choices=[('quiz', 'Quiz'), ('attendance', 'Attendance'), ('redemption', 'Redemption'), ('manual', 'Manual'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Number of points earned/spent/adjusted.')),
                ('description', models.TextField(blank=True, help_text="Short explanation, e.g. 'Quiz 1 reward', 'Redeemed E-book X'.", null=True)),
                ('on_chain_tx_hash', models.CharField(blank=True, help_text='Blockchain hash for this points operation, if applicable.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('ebook', 'E-Book'), ('pdf', 'PDF / Notes'), ('course', 'Course Access'), ('mock_test', 'Mock Test / Practice Pack'), ('voucher', 'Voucher / Coupon'), ('physical', 'Physical Item'), ('other', 'Other')], default='ebook', max_length=20)),
                ('points_price', models.PositiveIntegerField(help_text='How many points are required to redeem one unit of this product.')),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited (digital) items.', null=True)),
                ('is_digital', models.BooleanField(default=True, help_text='If false, assume this is a physical item.')),
                ('digital_file', models.FileField(blank=True, help_text='Upload file for e-books/notes if applicable.', null=True, upload_to='marketplace/digital_products/')),
                ('external_url', models.URLField(blank=True, help_text='External link (LMS, course platform, etc.) if applicable.', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='marketplace/product_thumbnails/')),
                ('metadata', models.JSONField(blank=True, help_text="Optional extra data (e.g. 'publisher', 'subject', etc.).", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='If true, can be highlighted in the marketplace UI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('points_spent', models.PositiveIntegerField(help_text='Total points spent for this redemption (quantity * product.points_price).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tx_hash', models.CharField(blank=True, help_text='On-chain transaction hash for this redemption.', max_length=100, null=True)),
                ('delivery_email', models.EmailField(blank=True, help_text='Where digital items / codes may be sent.', max_length=254, null=True)),
                ('delivery_notes', models.TextField(blank=True, help_text='Optional notes related to delivery or fulfilment.', null=True)),
                ('shipping_address', models.TextField(blank=True, help_text='Optional: address for physical items.', null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='marketplace.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
