# Generated by Django 5.2.8 on 2025-12-08 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq_single', 'MCQ - Single Correct'), ('mcq_multiple', 'MCQ - Multiple Correct'), ('true_false', 'True/False'), ('short_text', 'Short Text')], default='mcq_single', max_length=20)),
                ('marks', models.FloatField(default=1.0)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of question within quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='users.classgroup')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='users.institution')),
                ('teacher', models.ForeignKey(blank=True, help_text='Primary teacher/creator of this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('institution', 'Institution Only'), ('class', 'Class Only')], default='public', max_length=20)),
                ('delivery_type', models.CharField(choices=[('video', 'Video'), ('vr', 'VR'), ('ar', 'AR'), ('hybrid', 'Hybrid')], default='video', max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('resource_link', models.URLField(blank=True, help_text='Optional main link to PPT/notes/etc.', null=True)),
                ('vr_scene_id', models.CharField(blank=True, help_text='ID or slug used by the VR client to load this environment', max_length=100, null=True)),
                ('ar_experience_id', models.CharField(blank=True, help_text='ID for AR experience, if applicable', max_length=100, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='If this is a live/scheduled lecture', null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Approx duration, for UI only', null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='users.classgroup')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectures.course')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='users.institution')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher delivering this lecture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('note', 'Note'), ('pdf', 'PDF'), ('ebook', 'E-Book'), ('slides', 'Slides'), ('assignment', 'Assignment'), ('link', 'External Link'), ('other', 'Other')], default='pdf', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Upload for PDFs, notes, ebooks, etc.', null=True, upload_to='learning_resources/')),
                ('external_url', models.URLField(blank=True, help_text='Optional external link (Drive, website, etc.)', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='If false, later you can restrict to enrolled students only.')),
                ('order', models.PositiveIntegerField(default=0, help_text='For ordering resources in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, help_text='Resource at course level (available for all lectures)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lectures.course')),
                ('lecture', models.ForeignKey(blank=True, help_text='Resource specific to a particular lecture', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lectures.lecture')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lectures.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Optional time limit for quiz', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lectures.lecture')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lectures.quiz'),
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('points_tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash if points were awarded', max_length=100, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lectures.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='lectures.question')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='lectures.option')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lectures.quizsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_seconds', models.PositiveIntegerField(default=0, help_text='Approx duration the student was present in the session')),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('points_tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='lectures.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lecture', 'student')},
            },
        ),
    ]
