# Generated by Django 5.2.8 on 2026-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='ar_experience_id',
            field=models.URLField(blank=True, help_text='ID for AR experience, if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='vr_scene_id',
            field=models.URLField(blank=True, help_text='ID or slug used by the VR client to load this environment', null=True),
        ),
    ]
