# Generated by Django 5.2.8 on 2026-01-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.CharField(blank=True, help_text='Private key for the wallet. Keep this secret!', max_length=66, null=True),
        ),
    ]
