# Generated by Django 5.2.8 on 2026-01-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.PositiveIntegerField(default=0, help_text='Daily login streak'),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='Experience Points'),
        ),
    ]
